name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run Migrations
      run: |
        python e2e/manage.py migrate

    - name: Run Tests
      run: |
        python e2e/manage.py test

  cd:
    name: Continuous Deployment
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Replit Deployment
      run: |
        curl -X POST \
        -H "Authorization: my_secret_key" \
        -H "Content-Type: application/json" \
        https://martinjohny29.AppDev.repl.co/webhook

    - name: Notify deployment
      run: echo "Your application is deployed and live at https://bf4b3700-4df4-46fa-99e2-793422b5c7f5-00-1c00gta23mbrk.spock.replit.dev/loginpage"


        
